### PR TITLE
Export with dataverse

### PR DESCRIPTION
**Pull request by langbart**
Hey Fer, I added this basic function to export files to Dataverse, I have not yet listed the token in the conf. file as we are not yet sure if we will use dataverse or something else. Anyway, you can easily sign up and take some tests and see if Dataverse is the best option. I think that is quite good and also well documented.

### CODE REVIEW

**Comment by efcaguab** [comment]
Cool stuff. I checked out the branch and tried it in my computer with a dummy Dataverse account. Works great! A couple of observations:

- Looks like the package `dataverse` is not in CRAN anymore so we might need to change our approach for reproducibility. One option (the easiest, I think) is to modify the dockerfile(s) and the DESCRIPTION file to indicate we use a specific release from GitHub. Another  option is to copy paste the code we use from that package into our package, but we'll need to check the license to see if we can do that. A third option is to use [pydataverse](https://pydataverse.readthedocs.io/en/latest/#) which looks more stable but that would mean using python instead. 
- Our main use case is that the dataset already exists and we want to update the file content. I think the current function, if called twice in a row, will create two different datasets instead of updating?

Anyways, lets wait until we know we can use this approach or not to make these adjustments. For now, lets put it down the priority list and focus on the weight code

**Comment by langbart** [comment]
Hey @efcaguab, happy that you liked it. I agree that the easiest solution is to modify the Docker file. For what concerns the updating of the files, I think that once a file is published with an associated DOI,  it can not be modified anymore. So we should just add new versions each n months.

**Comment by langbart** [comment]
Hey @efcaguab, just a little update on this branch. Fortunately, changing the docker R image solved the loading problem of the `dataverse` package. There are 3 main issues to solve

- Some metadata are correctly displayed in the dataverse portal while others are not.
- It is still not clear to me how to set different times for different jobs in the pipeline (that is, set the data export for every 6 months while keeping the rest of the pipeline running on each push).
- Which data we want to export (and publish) and if we have to do some specific preprocessing

**Comment by langbart** [comment]
Hey @efcaguab , this is what the peskas portal on Dataverse would look like https://demo.dataverse.org/dataverse/peskas. I still have to finish compiling the README document, but I think it's ok with the rest. I added a new workflow to upload data to dataverse (it  is currently set to every day on the demo server ). Let me know if you see that there is something wrong or you want to change something so I change the token and server from demo to official.

**Comment by efcaguab** [comment]
Looks great. I haven't had time to actually check the code (and I think I won't anymore :(, sorry!). From what I see in data verse I have couple questions observations? 

- Why are there 3 datasets there, one in Dec 11 and two for Dec 6? Is that from when you're trying? I thought there would be just one that would be updated?
- For testing a daily workflow looks perfect, but for production a weekly or monthly seems more appropriate. 
- I expected to see that the latest dataset would have different versions but when I click on the tab I only see one version. Is that the expected behaviour? Is a new version being currently uploaded daily?
- Would be good to check with Alex about other authors that might need to be included
- Of course that's up to you. I would remove all the ads and aggregated data from there and leave just the tsv. My reasoning is that at some point we going to be asked to document the files and describe every column in them. I tend to lean towards doing the minimum necessary and exclude the .rds files which have a lot of extra columns we might need to look into.

**Comment by langbart** [comment]
Hey @efcaguab  thanks for the comments and for spending some time on this. 
- I created several dataverse collections, the one you saw (December 6-11) was the last one. 
- The fact that the datasets are not versioned and are uploaded as single elements every time is expected at the moment since the API to create different versions is a bit problematic and seemed unstable to me (however I'm working on it). 
- I agree with the removal of the rds files, it was one of the things I was wondering.
- I just realized that the schedule on github actions works (only?) on main and not for other branches. I am looking to solve this thing

**Comment by langbart** [comment]
Close #21

**Pull request merged**
