### PR TITLE
Feat pds data

### PR DESCRIPTION
**Pull request by efcaguab**

### CODE REVIEW

**Comment by efcaguab** [comment]
Hi Lorenzo. Just adding/editing some of the code you did. Great to see it. Here a list of what I've done, plan to do: 

- [x] Removed the option of downloading PDS trips as json. The API actually only uses csv and if you notice the file contents of the json data is actually identical. See 36ac29f5f884b85ff8a06fc8e1e6652f5350dd18
- [x] Use the timor (and timor-dev) bucket for the trips. As we handle that file the same as the surveys. It makes sense to keep the tracks on its own bucket because they get handled differently. See 1a65856e77fbce11f5bebf4d7c0477ef7fb5c006
- [x]  Edit the track ingestion so that it depends on the trip ingestion. Currently we download the trips twice, once when we ingest the trips and another time when we ingest the tracks. Might be better to have the tracks depending on the trips for consistency. See 83b7c17636fa8d20dc3d23b9cbb1bba39a0573be
- [ ] There is some code duplication. For example `retrieve_pds_tracks_data()` and `retrieve_pds_trips_data()` already do a their job well but that's duplicated by `get_pds_resp()`
- [ ] Still save tracks with versioning info but not use it. This will help us to know when a track was ingested the version of the code that was used for that
- [ ] Not sure if merging track and trip information is needed as , for now, most of the info we need is in the trips one and integrating these two

**Comment by efcaguab** [comment]
Another potential problem with using `get_pds_resp()` is that the trips csv is a mess because PDS did not separated fields properly for the gear. So some records end up having more columns than expected and the IMEI and Device id don't get parsed properly. Not something we need to fix now but something to keep in mind for later

**Comment by efcaguab** [comment]
@langbart I'll leave it running on my laptop for a while to see how it works and let you know :)

**Comment by langbart** [comment]
Wow @efcaguab, there were many things to clean! The issue about trips and tracks merging is not very clear to me, in particular on what type of file and structure to return... Maybe let's talk about it in the next catch up.

**Comment by efcaguab** [comment]
Sure lets chat in the next catch up! 

I did a couple more changes 

- Compress the files before uploading them to the bucket so that we don't have to pay as much for storage
- Run the jobs in parallel. The bottleneck in the algorithm was contacting the PDS api and uploading the files to Google Cloud. During that time the cores and disk are not doing much. I started with processing 32 trips at a time and looks like doing it that way we may be able download all the tracks within the 6 hour limit per job in Github Actions

**Comment by efcaguab** [comment]
Fixed on #39

**Pull request merged**
